config/routes.rb
# https://railstutorial.jp/chapters/password_reset?version=5.1#cha-password_reset
# 12章から

# https://railstutorial.jp/chapters/account_activation?version=5.1#sec-generalizing_the_authenticated_method
# 11.3.1 authenticated?メソッドの抽象化 を復習

# 送信メールプレビュー
# /sample_app/config/environments/development.rb
# host = 'rails-tutorial-wmain.c9users.io'
# ブラウザに付け足すURL
# /rails/mailers/user_mailer/account_activation
# /rails/mailers/user_mailer/password_reset


# boolen型のカラム、adminなどを作るとrailsでは自動的に論理値を返すadmin?メソッドが使える。

Rails.application.routes.draw do

  root 'words#index'
  get  '/words/comparison', to: 'words#comparison'
  get  '/answer',           to: 'words#answer'
  get  '/result',           to: 'words#result'

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # resourcesは全て複数形となる！！
  resources :users
  resources :words
  resources :account_activations, only: [:edit]
end

# tips
# cap11 メールでのアカウント有効化
#
# 1, 有効化トークンと有効化digestを関連付ける。
# 2, 有効化トークンをユーザーにメールする。
# 3, ユーザーがそのリンクをクリックすると有効化できるようにする。

# 上記を実装する段取り
# 1, ユーザーの初期状態はunactivatedにする
# 2, ユーザー登録が行われた時、activation_tokenとactivation_digestを生成
# 3, activation_digestはDBに保存し、　activation_tokenはメールで送る。
# 4, ユーザーがメールのリンクをクリックしたら、メールアドレスをキーにしてユーザーを探し、
#    DB内にあるactivation_digestと比較し、認証する。
# 5, ユーザーを認証できたら有効化済み(activated)にする。


# tips
# メールの送信内容について：
#
# railsサーバーでユーザーをメールアドレスで検索して有効化トークンを認証できるようにする
# のでリンクにはメールアドレスとactivation_tokenを含める。
# edit_account_activation_url(@user.activation_token)
# は
# edit_user_url(user)
# が
# http://www.example.com/users/1/edit
# を表すことにあてはまると
# http://www.example.com/account_activations/q5lt38hQDc_959PVoo6b7A/edit
# となる。さらに、urlの最後に?を追加し、それ以降にキーと値のペアを付けた形は以下となる。
# account_activations/q5lt38hQDc_959PVoo6b7A/edit?email=foo%40example.com

# これをリンクで表記するとすると、
# edit_account_activation_url(@user.activation_token, email: @user.email)
# となる。


# cap12 パスワード再設定
#
# PasswordResetsリソースを作成し、再設定用トークンとそれに対応するdigestを保存するのが今回
# の目的となる。

# 1、ユーザーがパスワード再設定をリクエストすると、ユーザーが送信したメールアドレスをキーにして
# データベースからユーザーを見つける。
# 2、該当のメールアドレスがDBにある場合は再設定用tokenと対応するdigestを生成。
# 3、再設定用digestはDBに保存しておき、再設定用tokenはメールアドレスと一緒に、ユーザーに送信
# する有効化用のメールのリンクに組み入れる。
# 4、ユーザーがメールのリンクをクリックしたら、メールアドレスをキーとしてユーザーを探し、DB内に
# 保存してある再設定用digestと比較し、トークンを認証する。
# 5、認証に成功したら、パスワード変更用のフォームをユーザーに表示する。

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }

  # tips
  # has_secure_password：
  # ・ハッシュ化したパスワードを、password_digestに保存できるようになる。
  # ・2つのペアの仮想的（DBに存在しない)な属性のpasswordとpassword_confirmation
  # が使えるようになる。
  # ・authenticateメソッドが使えるようになる。
  # ・機能させるにはpassword_digest属性がモデル内に必要。
  # digestにはハッシュ化（元に戻せないので暗号化ではない）されたpasswordが入る。

  has_secure_password
  validates :password, presence: true, length: { minimum: 6}, allow_nil: true

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # tips
  # ユーザーの暗号化済みIDと記憶トークンをブラウザの永続cookiesに保存する。
  # cookiesメソッドを使う。このメソッドはsessionと同様、ハッシュとして使える。
  # cookiesはvalueとオプションのexpires(有効期限)からできている。
  # remember_tokenと同じ値をcookiesに保存することで永続的なセッションを作る。
  # user.idのcookiesへの保存はsignedを使い署名つきにする。
  # ユーザーIDと記憶トークンはペアで扱う必要があるので、user.idを保存するcookiesも永続化する。
  # cookies.signed[user_id]で自動的にユーザーIDの暗号が解除されてfind_byで使えるようになる。
  # 次にbcryptを使って、cookies[:remember_token]とremrmber_digestが一致することを確認。
  # cookies[:remember_token]は暗号化されたユーザーIDと共にブラウザに20年保存。
  # ブラウザに保存されたremember_tokenとremember_digestを比較する。
  # has_secure_passwordで提供されているauthenticateメソッドと似ている。

  # 渡されたtokenがdigestと一致したらtrueを返す
  # ここでのremember_tokenはアクセラのremember_tokenとは別のローカル変数。
  # def authenticated?(remember_token)
  #   # digestが存在しない場合は処理を終了
  #   return false if remember_token
  #   BCrypt::Password.new(remember_digest).is_password?(remember_token)
  # end

  # 11.3.1 authenticated?メソッドの抽象化のために上記メソッドを改良
  def authenticated?(attribute, token)
    # digestが存在しない（nil）の場合(2つのブラウザで片方でログアウトした時など)
    # falseを返す。returunで即座にメソッドを終了している。
    
    # sendを使って抽象化
    digest = send("#{attribute}_digest")
    
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # アカウントを有効にする
  def activate
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # 有効化用のメールを送信する
  def send_activation_email
    # UserMailer.account_activation(self).deliver_now
    # チュートリアル通りの上記の書き方ではメール文が（日本語？）base64でエンコーディングされて
    # しまった。
    # cloud9ではこのような現象は起きなかった。

    # メール送信でエラーが出る時
    # Content-Transfer-Encoding: base64 となってしまう時
    # http://d.hatena.ne.jp/takahashim/20101201/p1

    mail = UserMailer.account_activation(self)
    mail.transport_encoding = "8bit"
    mail.deliver
  end

  private
    # メールアドレスを全て小文字にする
    def downcase_email
      self.email = email.downcase
    end

    # activation_tokenとacitvation_digestを作成し、代入する。
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

# tips
# 11.3.1 authenticated?メソッドの抽象化
#
# activation_tokenとemailをそれぞれparams[:id]とparams[:email]として参照できる。
# activation_tokenは、
# http://www.example.com/account_activations/q5lt38hQDc_959PVoo6b7A/edit
# としてidのように扱われているために、params[:id]として参照できる。
#
# 次のようなコードでユーザーを検索して認証する。
# user = User.find_by(email: params[:email])
# if user && user.authenticated?(:activation, params[:id])
# 
# 上のコードで使っているauthenticated?メソッドはアカウント有効化のdigestと渡されたtokenが
# （引数:activationにdigestを渡す）一致するかを検証する。
# ただし、この下記メソッドはremember_tokenようなのでactivationでは使えない。

# tokenがdigestと一致したらtrueを返す

# def authenticated?(remember_token)
#   return false if remember_digest.nil?
#   BCrypt::Password.new(remember_digest).is_password?(remember_token)
# end

# BCryptを使ってcookies[:remember_token]がremember_digestと一致するか確認。
# is_password?は==の再定義。一致しているか確認している。

# remember_digestはUserモデル属性なので、モデル内では
# self.remember_digest と書ける。

# 上記コードのrememberの部分を変数として扱いたい。状況に応じて切り替えたい。

#
# 受け取ったパラメータに応じて呼び出すメソッドを切り替える手法を使う。【メタプログラミング】
#

# railsコンソールを開き、Rubyオブジェクトに対してsendメソッドを実行して配列の長さを取るとする
# a = [1, 2, 3]
# a.length
# =>3
# a.send(:length)
# =>3
# a.send("length")
# =>3

# この時sendを通して渡したシンボル:lengthや文字列"length"はいずれもlenghtメソッドと同じ
# 結果となる。どちらもオブジェクトにlengthメソッドを渡しているため等価。

# もう一つの例
# user = User.first
# user.activation_digest
# =>"$2a$10$4e6TFzEJAVNyjLv8Q5u22ensMt28qEkx0roaZvtRcp6UZKR
# user.send(:activation_digest)
# =>"$2a$10$4e6TFzEJAVNyjLv8Q5u22ensMt28qEkx0roaZvtRcp6UZKR
# user.send("activation_digest")
# =>"$2a$10$4e6TFzEJAVNyjLv8Q5u22ensMt28qEkx0roaZvtRcp6UZKR
# attribute = :acrivation
# user.send("#{attribute}_digest")
# =>"$2a$10$4e6TFzEJAVNyjLv8Q5u22ensMt28qEkx0roaZvtRcp6UZKR

# 文字列の式展開によって引数を組み立てsendに渡している。

# 文字列'activation'でも同じことができるが、Rubyではシンボルを使う方が一般的。

#
# sendメソッドの動作原理がわかったので、これを使ってauthenticated?メソッドを書き換える。
#

# def authenticated?(remember_token)
#   digest = self.send("remember_digest")
#   return false if digest.nil?
#   BCrpt::Password.new(digest).is_password?(remember_token)
# end

# 上記コードの各引数を一般化し、文字列を式展開する。sendの前のselfは省略できる。
# def authenticated?(attribute, token)
#   digest = send("#{attribute}_digest")
#   return false if digest.nil?
#   BCrypt::Password.new(digest).is_password?(token)
# end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ApplicationControllerでSessionhelperをincludeしている
  
  before_action :logged_in_user, only: [:index, :edit, :update] # :index
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    # @users = User.all
    # paginateのために下記の入れ方にする
    @users = User.where(activated: true).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    redirect_to root_url and return unless @user.activated?
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "word appへようこそ!ユーザー認証メールを送信しました"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # 更新に成功した場合
      flash[:success] = "編集が成功しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # beforeアクション

    # ログイン済みユーザーかどうかを確認
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end

    # 正しいユーザーかどうか確認(current_userではないことに注意)
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
                

</li>

app/views/users/edit.html.erb
<!-- railsはDBにユーザーがいるかどうかでPOSTかPATCHを判断している。 -->
<!-- そのため特別な記述をしなくてもeditページだと判断している。 -->

<h1>ユーザー編集ページ</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <br>
      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
    <!-- <table class="table">
      <tr bgcolor="silver">
        <th>名前</th><th>メールアドレス</th>
      </tr>
      <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user.id) %></td><td><%= user.email %></td>
      </tr>
      <% end %>
    </table> -->
    <%# Railsは@userをUserオブジェクトのリストであると推測する。さらに、ユーザーのコレクション
    を与えて呼び出すと、Railsは自動的にユーザーのコレクションを列挙しそれぞれのユーザーを
    パーシャルで出力する。 %>
    <%# <% @users.each do |user| %>

<p>ユーザー一覧</p>
<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<div class="jumbotron">
  <p>新規ユーザー登録</p>
  <br>
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :name, "名前" %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password, class: 'form-control' %>

    <%= f.label :password_confirmation, "パスワード確認" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
    <br>
    <%= f.submit "登録", class: "btn btn-primary" %>
  <% end %>

  <%= "#{session[:user_id]}" %>



</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %> | <%= @user.email %> | <%= @user.admin %>
      </h1>
    </section>
  </aside>
</div>

<%= "#{@user[:name]}" %>
<%= "#{@user[:id]}" %>

<!--<table class="table">-->
<!--  <tr><th>名前</th><th>メールアドレス</th></tr>-->
<!--  <tr><td><%#= @user.name %></td><td><%#= @user.email %></td></tr>-->
<!--</table>-->